### ISSUE TITLE
alhPdfViewController?.setZoom,the application Exited

### ISSUE THREAD

**Issue by YuhooZhu** [alhappler/alh_pdf_view#32] opened 2022-12-05 04:41 UTC
The application may be doing too much work on its main thread.
here is my log.
```
( 3677): Starting a blocking GC Alloc
I/art     ( 3677): Alloc sticky concurrent mark sweep GC freed 2491(79KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 307us total 5.856ms
I/art     ( 3677): Starting a blocking GC Alloc
I/art     ( 3677): Clamp target GC heap from 104MB to 96MB
I/art     ( 3677): Alloc partial concurrent mark sweep GC freed 98(3KB) AllocSpace objects, 11(7MB) LOS objects, 8% free, 88MB/96MB, paused 517us total 10.474ms
3
I/art     ( 3677): Starting a blocking GC Alloc
I/art     ( 3677): Clamp target GC heap from 108MB to 96MB
I/art     ( 3677): Alloc partial concurrent mark sweep GC freed 67(2176B) AllocSpace objects, 5(3MB) LOS objects, 3% free, 92MB/96MB, paused 370us total 13.506ms
I/art     ( 3677): Clamp target GC heap from 111MB to 96MB
I/art     ( 3677): Alloc partial concurrent mark sweep GC freed 50(4KB) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 123us total 14.053ms
I/art     ( 3677): Starting a blocking GC Alloc
I/art     ( 3677): Clamp target GC heap from 111MB to 96MB
I/art     ( 3677): Alloc concurrent mark sweep GC freed 4(152B) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 218us total 16.575ms
I/art     ( 3677): Forcing collection of SoftReferences for 703KB allocation
I/art     ( 3677): Starting a blocking GC Alloc
I/art     ( 3677): Clamp target GC heap from 111MB to 96MB
I/art     ( 3677): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 384us total 15.157ms
W/art     ( 3677): Throwing OutOfMemoryError "Failed to allocate a 720012 byte allocation with 287776 free bytes and 281KB until OOM"
I/art     ( 3677): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 313us total 17.339ms
I/art     ( 3677): Forcing collection of SoftReferences for 703KB allocation
I/art     ( 3677): Starting a blocking GC Alloc
I/art     ( 3677): Clamp target GC heap from 111MB to 96MB
I/art     ( 3677): Alloc concurrent mark sweep GC freed 3(72B) AllocSpace objects, 0(0B) LOS objects, 0% free, 95MB/96MB, paused 537us total 14.323ms
W/art     ( 3677): Throwing OutOfMemoryError "Failed to allocate a 720012 byte allocation with 287776 free bytes and 281KB until OOM"
E/AndroidRuntime( 3677): FATAL EXCEPTION: PDF renderer
E/AndroidRuntime( 3677): Process: com.example.pdf_tv, PID: 3677
E/AndroidRuntime( 3677): java.lang.OutOfMemoryError: Failed to allocate a 720012 byte allocation with 287776 free bytes and 281KB until OOM
E/AndroidRuntime( 3677): 	at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
E/AndroidRuntime( 3677): 	at android.graphics.Bitmap.nativeCreate(Native Method)
E/AndroidRuntime( 3677): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:879)
E/AndroidRuntime( 3677): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:856)
E/AndroidRuntime( 3677): 	at android.graphics.Bitmap.createBitmap(Bitmap.java:823)
E/AndroidRuntime( 3677): 	at com.github.barteksc.pdfviewer.RenderingHandler.proceed(RenderingHandler.java:102)
E/AndroidRuntime( 3677): 	at com.github.barteksc.pdfviewer.RenderingHandler.handleMessage(RenderingHandler.java:66)
E/AndroidRuntime( 3677): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 3677): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime( 3677): 	at android.os.HandlerThread.run(HandlerThread.java:61)
I/Choreographer( 3677): Skipped 93 frames!  The application may be doing too much work on its main thread.
I/Choreographer( 3677): Skipped 57 frames!  The application may be doing too much work on its main thread.
D/jniPdfium( 3677): Destroy FPDF library
E/libEGL  ( 3677): call to OpenGL ES API with no current context (logged once per thread)
Lost connection to device.
Exited (sigterm)
```
thanks

**Comment by andreBalh** [comment] 2022-12-05 06:24
Hello @YuhooZhu 
Thank you for opening the issue.
Can you reproduce this issue easily or does this happen only sometimes? @YuhooZhu

**Comment by YuhooZhu** [comment] 2022-12-05 06:31
> Hello @YuhooZhu Thank you for opening the issue. Can you reproduce this issue easily or does this happen only sometimes? @YuhooZhu

I'm a new user of Flutter. I don't know whether it is related to GC of different Android versions

**Comment by andreBalh** [comment] 2022-12-05 06:32
Ok, I will check that and try to fix that issue. 👍  @YuhooZhu

**Comment by andreBalh** [comment] 2022-12-05 06:34
And do you have a code snippet how you call `.setZoom`? @YuhooZhu

**Comment by YuhooZhu** [comment] 2022-12-05 06:40
```
import 'dart:developer';

import 'package:alh_pdf_view/lib.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';

class PDFScreen extends StatefulWidget {
  final String? path;
  PDFScreen({Key? key, this.path}) : super(key: key);

  _PDFScreenState createState() => _PDFScreenState();
}

class _PDFScreenState extends State<PDFScreen> {
  int? pages = 0;
  int? currentPage = 0;
  bool isReady = false;
  String errorMessage = '';
  AlhPdfViewController? alhPdfViewController;

  double zoomOrigin = 1.0;
  Future<double> zoomChange(double size) async {
    if (zoomOrigin > 0.99 && zoomOrigin <= 10.0) {
      zoomOrigin += size;
    } else {
      zoomOrigin = 1.0;
    }
    log(zoomOrigin.toString());
    return zoomOrigin;
  }

  Future<void> zoomReset() async {
    zoomOrigin = 1.0;
    alhPdfViewController?.resetZoom();
  }

  Future<void> _handleZoom(double size) async {
    await alhPdfViewController!.setZoom(zoom: await zoomChange(size));
  }

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("xx"),
        leading: GestureDetector(
          onTap: () {
            Navigator.of(context).popAndPushNamed("/search", arguments: "xx");
          },
          child: const Icon(Icons.arrow_left),
        ),
      ),
      body: Listener(
        onPointerSignal: (event) {
          if (event is PointerScrollEvent) {
            log(event.scrollDelta.dy.toString());
            setState(() {
              _handleZoom(event.scrollDelta.dy);
            });
          }
        },
        child: AlhPdfView(
          filePath: widget.path,
          enableSwipe: true,
          swipeHorizontal: true,
          autoSpacing: false,
          pageFling: true,
          pageSnap: true,
          defaultPage: currentPage!,
          fitPolicy: FitPolicy.both,
          enableDefaultScrollHandle: true,
          minZoom: 1.0,
          maxZoom: 10.0,
          onRender: (_pages) {
            setState(() {
              pages = _pages;
              isReady = true;
            });
          },
          onError: (error) {
            setState(() {
              errorMessage = error.toString();
            });
            print(error.toString());
          },
          onPageError: (page, error) {
            setState(() {
              errorMessage = '$page: ${error.toString()}';
            });
            print('$page: ${error.toString()}');
          },
          onViewCreated: (controller) {
            alhPdfViewController = controller;
          },
          onPageChanged: (int? page, int? total) {
            print('page change: $page/$total');
            setState(() {
              currentPage = page;
            });
          },
        ),
      ),
    );
  }
}
```
Here is my code , but i tested your example found that the error happen on Android 7 or 8 too.

**Comment by andreBalh** [comment] 2022-12-05 06:42
Ok, that helps a lot, thank you @YuhooZhu

**Comment by andreBalh** [comment] 2024-03-28 15:21
Hello @YuhooZhu after a long time,
I will close this issue because it's hard for me to reproduce it, I think in the end, the package is not optimized for older devices. If this issue is still serious for you, you can reopen it

**Closed by andreBalh** 2024-03-28 15:21 UTC
Labels: bug
